---

- name: install on redhat host
  import_tasks: redhat/install.yml
  when: (ansible_os_family | lower == "redhat")

- name: install debian host
  import_tasks: debian/install.yml
  when: (ansible_os_family | lower == "debian")
