---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: filebeat-rh7
    image: solita/centos-systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: filebeat-ubuntu16
    image: solita/ubuntu-systemd:latest
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    diff: false
    become: true
  env:
    ANSIBLE_HASH_BEHAVIOUR: merge

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: flake8
    enabled: false
