---

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-filebeat
      filebeat:
        options:

          filebeat:
            prospectors:
              - document_type: syslog
                paths:
                  - /var/log/cron
                  - /var/log/secure
                  - /var/log/messages
                type: log

          output:
            file:
              path: "/tmp/filebeat"
              filename: filebeat
