---

- name: ensure dependencies are installed
  package:
    name:
      - yum-utils
      - libselinux-python

- name: ensure Elastic repository is present
  yum_repository:
    name: "elastic-{{ filebeat.version.split('.')[:1] | join('.') }}.x"
    description: "Elastic repository for version {{ filebeat.version.split('.')[:1] | join('.') }}.x"
    file: "elastic-{{ filebeat.version.split('.')[:1] | join('.') }}.x"
    baseurl: "https://artifacts.elastic.co/packages/{{ filebeat.version.split('.')[:1] | join('.') }}.x/yum"
    gpgkey: "http://packages.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: ensure yum-plugin-versionlock is installed
  package:
    name: yum-plugin-versionlock
  when: filebeat.pin_version
